# Generated by Django 4.1.7 on 2023-04-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_authorprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
